# Generated by Django 3.0.6 on 2020-06-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200602_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationattempt',
            name='delta_days',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
    ]
