# Generated by Django 3.0.6 on 2020-06-04 18:40

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import BtreeGinExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_event_prevalent_when'),
    ]

    operations = [
        BtreeGinExtension(),
        migrations.AddIndex(
            model_name='event',
            index=django.contrib.postgres.indexes.GinIndex(fields=['title', 'description'], name='app_event_title_4db519_gin'),
        ),
    ]
