# Generated by Django 3.0.7 on 2020-06-08 08:35

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_event_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='when',
            name='specificity',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
