# Generated by Django 3.0.7 on 2020-06-08 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_when_specificity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='when',
            name='specificity',
            field=models.CharField(choices=[('year', 'Year'), ('season', 'Season'), ('month', 'Month'), ('day', 'Day')], max_length=100),
        ),
    ]
