# Generated by Django 3.0.7 on 2020-06-08 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200608_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='when',
            name='specificity',
            field=models.CharField(choices=[('year', 'Year'), ('season', 'Season'), ('month', 'Month'), ('day', 'Day')], default='day', max_length=100),
        ),
    ]
