# Generated by Django 3.0.7 on 2020-06-18 06:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200608_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('flagged', 'Flagged'), ('deleted', 'Deleted')], default='accepted', max_length=50),
        ),
        migrations.AlterField(
            model_name='when',
            name='sources',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), blank=True, default=list, null=True, size=None),
        ),
    ]
