# Generated by Django 3.0.7 on 2020-06-21 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0008_auto_20200618_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='sentiment',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('user', 'when')},
        ),
    ]
