# Generated by Django 3.0.7 on 2020-07-11 16:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200629_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('flagged', 'Flagged'), ('deleted', 'Deleted')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='config',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict),
        ),
    ]
