# Generated by Django 3.0.7 on 2020-09-19 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20200711_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('flagged', 'Flagged'), ('rejected', 'Rejected'), ('deleted', 'Deleted')], default='pending', max_length=50),
        ),
    ]
