# Generated by Django 3.1.2 on 2021-02-07 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20200919_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='when',
            name='title',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notificationattempt',
            name='result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
